# Generated by Django 3.0.5 on 2020-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headding_content', models.CharField(max_length=50)),
                ('image_content', models.ImageField(upload_to='')),
                ('content_paragraph', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Website_steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headding_step', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=2000)),
                ('card_image', models.ImageField(upload_to='')),
                ('headding_model', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=2000)),
                ('website_cont', models.ManyToManyField(to='Website.Website_content')),
            ],
        ),
    ]
