# Generated by Django 3.0.5 on 2020-05-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_steps',
            name='website_cont',
            field=models.ManyToManyField(related_name='website_steps', to='Website.Website_content'),
        ),
    ]
