# Generated by Django 3.0.5 on 2020-05-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20200512_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_content',
            name='image_content',
            field=models.ImageField(upload_to='Personal_Website/static/images'),
        ),
        migrations.AlterField(
            model_name='website_steps',
            name='website_cont',
            field=models.ManyToManyField(to='Website.Website_content'),
        ),
    ]
